image: node:13.10.1-alpine3.10

before_script:
    - apk add curl
    - npm i -g vercel

stages:
    - staging
    - production
    - dev
    - presentation
    - merge
    #- test

merge:
    stage: merge
    image: node:13.10.1-alpine3.10

    variables:
        #PREVIEW_URL: $CI_PROJECT_NAME-master.vercel.app
        PREVIEW_URL: dev-$CI_MERGE_REQUEST_IID-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME.sollar.app

    script:
        - curl -X GET -H "Authorization:Bearer cQQp4g7QaYvCXCA-pVqB" https://gitlab.com/api/v4/projects/27836716/merge_requests/7/notes -o output.txt
        - cat output.txt
        #- DEPLOYMENT_URL=$(vercel -t $VERCEL_TOKEN --confirm)
        #- echo $DEPLOYMENT_URL >vercel_deployment_url.txt
        #- vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN
        #- curl -X POST -H "Authorization:Bearer cQQp4g7QaYvCXCA-pVqB" -H "Content-Type:application/json" https://gitlab.com/api/v4/projects/27836716/merge_requests/7/notes -d '{"id":27836716, "merge_request_iid":7, "body":"This merge request is being automatically deployed with Vercel ([learn more](https://vercel.link/gitlab-learn-more)).  \nTo see the url of your deployment, click on the status icon below.\n\n:white_check_mark:Preview:$PREVIEW_URL}'
    
    only:
        - merge_requests

production:
    stage: production
    image: node:13.10.1-alpine3.10

    variables:
        #PREVIEW_URL: $CI_PROJECT_NAME-master.vercel.app
        PREVIEW_URL: sollar.app

    script:
        - DEPLOYMENT_URL=$(vercel -t $VERCEL_TOKEN --confirm --prod)
        - echo $DEPLOYMENT_URL >vercel_deployment_url.txt
        - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN
    
    artifacts:
        when: on_success
        paths:
            - vercel_deployment_url.txt
    
    only:
        - master

staging:
    stage: staging
    image: node:13.10.1-alpine3.10

    variables:
        #PREVIEW_URL: $CI_PROJECT_NAME-master.vercel.app
        PREVIEW_URL: staging.sollar.app

    script:
        - DEPLOYMENT_URL=$(vercel -t $VERCEL_TOKEN --confirm)
        - echo $DEPLOYMENT_URL >vercel_deployment_url.txt
        - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN
    
    artifacts:
        when: on_success
        paths:
            - vercel_deployment_url.txt
    
    only:
        - staging

dev:
    stage: dev
    image: node:13.10.1-alpine3.10

    variables:
        #PREVIEW_URL: $CI_PROJECT_NAME-master.vercel.app
        PREVIEW_URL: dev.sollar.app

    script:
        - DEPLOYMENT_URL=$(vercel -t $VERCEL_TOKEN --confirm)
        - echo $DEPLOYMENT_URL >vercel_deployment_url.txt
        - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN
    
    artifacts:
        when: on_success
        paths:
            - vercel_deployment_url.txt
    
    only:
        - dev

presentation:
    stage: presentation
    image: node:13.10.1-alpine3.10

    variables:
        #PREVIEW_URL: $CI_PROJECT_NAME-master.vercel.app
        PREVIEW_URL: presentation.sollar.app

    script:
        - DEPLOYMENT_URL=$(vercel -t $VERCEL_TOKEN --confirm)
        - echo $DEPLOYMENT_URL >vercel_deployment_url.txt
        - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN
    
    artifacts:
        when: on_success
        paths:
            - vercel_deployment_url.txt
    
    only:
        - presentation
