const locators = {

  LOGIN: {
      EMAIL: '[name="email"]',
      PASSWORD: '[type="password"]',
      REMEMBER: '[value="remember"]',
      XP_BTN_ENTRAR: `//span[contains(.,'Entrar')]`,
      XP_BTN_CRIAR_CONTA: `//span[contains(.,'Criar conta')]`
  },

  MENU: {
    XP_BTN_AREA:`//*[@id="root"]/div[1]/div/div/ul[1]/li[6]`,
    XP_BTN_CLIENTES: `//*[@id="root"]/div[1]/div/div/ul[1]/li[2]`,
    XP_BTN_EMPRESAS: `//*[@id="root"]/div[1]/div/div/ul[1]/li[3]`,
    XP_BTN_PACIENTES: `//*[@id="root"]/div[1]/div/div/ul[1]/li[7]`,
    XP_BTN_CONFIGURACOES: `//*[@id="root"]/div[1]/div/div/ul[2]/li[1]`,
  },

  AREA: {
    XP_LISTA:`//tr[@class="MuiTableRow-root"]`,
    XP_BTN_NOVA_AREA: `//div//span[contains(.,'Nova Área')]`,
    XP_BTN_DADOS_AREA: `//div/button[contains(.,'Dados da Área')]`,
    XP_BTN_BAIRROS:`//div/button[contains(.,'Bairros')]`,
    XP_BTN_PRESTADORES:`//div/button[contains(.,'Prestadores')]`,
    XP_BTN_CANCELAR:`//div//button[contains(.,'Cancelar')]`,
    XP_BTN_VOLTAR:`//div//button[contains(.,'Voltar')]`,
    XP_BTN_PROXIMO:`//div//button[contains(.,'Próximo')]`,
    XP_BTN_SALVAR:`//div//button[contains(.,'Salvar')]`,
    XP_BTN_MENU: `//*[@id="btn_area-menu0"]/span[1]`,
    XP_BTN_MENU_EDITAR: `//*[@id="area-menu0"]/div[3]/ul/li[1]`,
    XP_RESULTADO: `//*[@id="root"]/div[1]/main/div/table/tbody/tr/td/div/p[2]`,
    POPUP_MENU :'#alert-dialog-title',
    INPUT_NAME: '[id="input-name"]',
    ABASTECIMENTO_1_DIAS:'[aria-hidden="true"][data-index="0"]',
    ABASTECIMENTO_7_DIAS:'[aria-hidden="true"][data-index="1"]',
    DIA_SEMANA:'#combo-box-day-of-week',
    ESTADOS: '#combo-box-neigthborhoods-states',
    CIDADES: '#combo-box-neigthborhoods-city',
    BAIRROS: '#combo-box-neigthborhoods',
    FUNCOES:'#combo-box-profession',
    PRESTADOR:'#combo-box-users',
    SEARCH: '#search-input',
    MSG: '.Toastify__toast-body'
  },

  CLIENTES: {
    NOME: '#input-social-client',
    NOME_SOCIAL: '#input-social-name',
    CNPJ: '#input-fiscal-number',
    CEP: '#input-postal-code',
    ENDERECO: '#input-address',
    NUMERO: '#input-address-number',
    COMPLEMENTO: '#input-address-complement',
    BAIRROS: '#input-neighborhood',
    CIDADE: '#input-city',
    UF: '#input-address-uf',
    NOME_RESPONSAVEL: '#input-responsible-name',
    EMAIL:'#input-email',
    TELEFONE: '#input-cellphone',
    CELULAR: '#input-phone',
    SEARCH:'#search-input',
    BTN_SEARCH:'.MuiInputAdornment-root > .MuiButtonBase-root',
    XP_BTN_CANCELAR:`//span[contains(.,'Cancelar')]`,
    XP_BTN_SALVAR: `//span[contains(.,'Salvar')]`,
    BTN_NOME_FANTASIA: ':nth-child(2) > :nth-child(1) > .sc-gInsOo > .sc-ctaXAZ',
    XP_BTN_CLIENTE_EDITAR: `//span[contains(.,'Editar')]`,
    BTN_MENU:'#btn_patient-menu1 > .MuiButton-label > .MuiSvgIcon-root',
    BTN_MENU_EDITAR:'#patient-menu1 > .MuiPaper-root > .MuiList-root > [tabindex="0"]',
    XP_BTN_MENU_VISUALIZAR: `//*[@id="patient-menu0"]/div[3]/ul/li[2]`,
    XP_ATIVO: `//*[@id="root"]/div[1]/main/div/div/div[2]/div/div[3]/div/div[13]/label/span[1]/span[1]/span[1]`,
    XP_BTN_NOVO:`//button[contains(.,'Novo')]`,
    XP_MSG_CNPJ: `//*[@id="root"]/div[1]/main/div/div/div[2]/div/div[1]/div/div[3]/p`,
    XP_MSG_CEP: `//*[@id="root"]/div[1]/main/div/div/div[2]/div/div[3]/div/div[1]/div/p`,
    XP_MSG_TELEFONE: `//*[@id="root"]/div[1]/main/div/div/div[2]/div/div[3]/div/div[10]/p`,

  },

  PACIENTES: {
    XP_BTN_NOVO: `//span[contains(.,'Novo')]`,
    NOME: '#input-name',
    NOME_SOCIAL: '#input-social-name',
    DATA_NASC: '#input-fiscal-birthdate',
    SEXO: '#combo-box-gender',
    MAE:'#input-mother-name',
    NACIONALIDADE:'#input-nationality',
    CPF: '#input-fiscal-number',
    RG: '#input-nation-id',
    ORGAO_EMISSOR: '#input-emitting-organ',
    ESTADO_CIVIL: '#combo-box-marital-status',
    TIPO_SANGUINEO: '#combo-box-blood-type',
    CEP: '#input-postal-code',
    ENDERECO: '#input-address',
    NUMERO: '#input-address-number',
    COMPLEMENTO: '#input-address-complement',
    BAIRRO: '#input-neighborhood',
    CIDADE: '#input-city',
    UF: '#input-address-uf',
    AREAS: '#combo-box-areas',
    EMAIL: '#input-email',
    TELEFONE: '#input-telefone',
    CELULAR: '#input-cellphone',
    NOME_RESPONSAVEL: '#input-responsible-name',
    CELULAR_RESPONSAVEL: '#input-reponsable-phone',
    PARENTESCO: '#input-responsible',
    XP_BTN_VOLTAR:`//span[contains(.,'Voltar')]`,
    XP_BTN_SALVAR:`//span[contains(.,'Salvar')]`,
    BTN_MENU: '#btn_patient-menu0',
    BTN_MENU_EDITAR:'#patient-menu0 > .MuiPaper-root > .MuiList-root > [tabindex="0"]',
    SEARCH: '#search-input',
  },

  EMPRESAS: {
    XP_BTN_NOVO: `//span[contains(.,'Novo')]`,
    XP_BTN_SALVAR: `//*[@id="root"]/div[1]/main/div/div/div[2]/button[2]/span[1]`,
    XP_BTN_VOLTAR: `//span[contains(.,'Voltar')]`,
    BTN_SEARCH: '#search-input',
    NOME_SOCIAL: '#input-social-name',
    NOME_FANTASIA:'#input-fantasy-name',
    CNPJ: '#input-fiscal-number',
    CEP: '#input-postal-code',
    ENDERECO: '#input-address',
    NUMERO: '#input-address-number',
    COMPLEMENTO: '#input-address-complement',
    BAIRRO:'#input-neighborhood',
    CIDADE: '#input-city',
    UF: '#input-address-uf',
    NOME_RESPONSAVEL: '#input-responsable-name',
    TELEFONE:'#input-phone',
    EMAIL: '#input-email',
    CELULAR:'#input-cellphone',
  }

}


export default locators;
